import React, { useState, useRef } from 'react'
import { X, Upload, FileText, Image, Loader2 } from 'lucide-react'

interface PDFImporterProps {
  isOpen: boolean
  onClose: () => void
  onImport: (file: File) => Promise<void>
  onImportImage: (file: File) => Promise<void>
  language?: string
}

const translations = {
  es: {
    title: 'Importar CV existente',
    subtitle: 'Sube tu CV en PDF o imagen para completar tu información automáticamente',
    warningPDF: '⚠️ Los PDFs generados por esta app no se pueden reimportar (son imágenes)',
    warningPDFDetail: 'Solo importa PDFs con texto seleccionable (Word, Google Docs, etc.)',
    dragText: 'Arrastra tu archivo aquí',
    orText: 'o selecciona',
    selectPDF: 'Importar PDF',
    selectImage: 'Importar imagen',
    formatTextPDF: 'PDF con texto seleccionable • Máximo 10MB',
    formatTextImage: 'JPG, PNG, WEBP • Captura de pantalla de tu CV • Máximo 10MB',
    processing: 'Procesando con IA...',
    processingSubtext: 'Esto puede tardar unos segundos',
    cancel: 'Cancelar',
    errorTooLarge: 'El archivo es demasiado grande. Máximo 10MB',
    errorInvalidFile: 'Formato no soportado. Usa PDF, JPG, PNG o WEBP',
  },
  en: {
    title: 'Import existing CV',
    subtitle: 'Upload your CV as PDF or image to auto-fill your information',
    warningPDF: '⚠️ PDFs generated by this app cannot be reimported (they are images)',
    warningPDFDetail: 'Only import PDFs with selectable text (Word, Google Docs, etc.)',
    dragText: 'Drag your file here',
    orText: 'or select',
    selectPDF: 'Import PDF',
    selectImage: 'Import image',
    formatTextPDF: 'PDF with selectable text • Maximum 10MB',
    formatTextImage: 'JPG, PNG, WEBP • Screenshot of your CV • Maximum 10MB',
    processing: 'Processing with AI...',
    processingSubtext: 'This may take a few seconds',
    cancel: 'Cancel',
    errorTooLarge: 'File is too large. Maximum 10MB',
    errorInvalidFile: 'Unsupported format. Use PDF, JPG, PNG or WEBP',
  },
}

const PDFImporter: React.FC<PDFImporterProps> = ({ isOpen, onClose, onImport, onImportImage, language = 'es' }) => {
  const [isDragging, setIsDragging] = useState(false)
  const [isProcessing, setIsProcessing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [mode, setMode] = useState<'pdf' | 'image'>('pdf')
  const pdfInputRef = useRef<HTMLInputElement>(null)
  const imageInputRef = useRef<HTMLInputElement>(null)
  const t = translations[language as keyof typeof translations] || translations.es

  if (!isOpen) return null

  const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); setIsDragging(true) }
  const handleDragLeave = (e: React.DragEvent) => { e.preventDefault(); setIsDragging(false) }

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer.files[0]
    if (file) await processFile(file)
  }

  const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) await processFile(file)
  }

  const processFile = async (file: File) => {
    setError(null)
    const isPDF = file.type === 'application/pdf'
    const isImage = file.type.startsWith('image/')

    if (!isPDF && !isImage) {
      setError(t.errorInvalidFile)
      return
    }

    if (file.size > 10 * 1024 * 1024) {
      setError(t.errorTooLarge)
      return
    }

    try {
      setIsProcessing(true)
      if (isPDF) {
        setMode('pdf')
        await onImport(file)
      } else {
        setMode('image')
        await onImportImage(file)
      }
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al procesar el archivo')
    } finally {
      setIsProcessing(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-end sm:items-center justify-center z-50 p-0 sm:p-4">
      <div className="bg-[#1C1C1E] border border-[#3A3A3C] rounded-t-3xl sm:rounded-3xl w-full sm:max-w-lg shadow-2xl animate-slide-up">
        {/* Header */}
        <div className="flex items-start justify-between p-6 pb-4">
          <div>
            <h2 className="text-lg font-bold text-white">{t.title}</h2>
            <p className="text-sm text-white/50 mt-0.5">{t.subtitle}</p>
          </div>
          <button onClick={onClose} disabled={isProcessing} className="p-2 text-white/40 hover:text-white hover:bg-white/10 rounded-xl transition-all disabled:opacity-40">
            <X size={18} />
          </button>
        </div>

        <div className="px-6 pb-6 space-y-4">
          {/* Mode toggle */}
          <div className="flex gap-1.5 p-1 bg-[#0F0F0F] rounded-xl border border-[#38383A]">
            <button
              onClick={() => setMode('pdf')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-xs font-semibold transition-all ${mode === 'pdf' ? 'bg-[#2C2C2E] text-white' : 'text-white/40 hover:text-white/70'}`}
            >
              <FileText size={13} /> PDF
            </button>
            <button
              onClick={() => setMode('image')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-xs font-semibold transition-all ${mode === 'image' ? 'bg-violet-600 text-white' : 'text-white/40 hover:text-white/70'}`}
            >
              <Image size={13} /> {language === 'es' ? 'Imagen' : 'Image'}
            </button>
          </div>

          {/* Warning for PDF */}
          {mode === 'pdf' && (
            <div className="p-3 bg-yellow-500/10 border border-yellow-500/25 rounded-xl">
              <p className="text-xs font-semibold text-yellow-400">{t.warningPDF}</p>
              <p className="text-[11px] text-yellow-400/70 mt-0.5">{t.warningPDFDetail}</p>
            </div>
          )}

          {/* Drop Zone */}
          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onClick={() => !isProcessing && (mode === 'pdf' ? pdfInputRef : imageInputRef).current?.click()}
            className={`border-2 border-dashed rounded-2xl p-8 text-center transition-all cursor-pointer
              ${isDragging
                ? 'border-violet-500 bg-violet-500/10'
                : 'border-[#3A3A3C] bg-[#0F0F0F] hover:border-violet-500/50 hover:bg-violet-500/5'}
              ${isProcessing ? 'opacity-50 cursor-not-allowed pointer-events-none' : ''}
            `}
          >
            {isProcessing ? (
              <div className="flex flex-col items-center gap-3">
                <Loader2 className="animate-spin text-violet-400" size={40} />
                <p className="text-white/70 font-medium text-sm">{t.processing}</p>
                <p className="text-white/40 text-xs">{t.processingSubtext}</p>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-3">
                {mode === 'pdf'
                  ? <FileText size={40} className={isDragging ? 'text-violet-400' : 'text-white/25'} />
                  : <Image size={40} className={isDragging ? 'text-violet-400' : 'text-white/25'} />
                }
                <p className="text-white/60 text-sm font-medium">{t.dragText}</p>
                <p className="text-white/30 text-xs">{t.orText}</p>
                <button
                  type="button"
                  className="px-5 py-2 bg-violet-600 hover:bg-violet-500 text-white rounded-xl text-sm font-semibold transition-all"
                  onClick={(e) => { e.stopPropagation(); (mode === 'pdf' ? pdfInputRef : imageInputRef).current?.click() }}
                >
                  {mode === 'pdf' ? t.selectPDF : t.selectImage}
                </button>
                <p className="text-white/25 text-[11px]">
                  {mode === 'pdf' ? t.formatTextPDF : t.formatTextImage}
                </p>
              </div>
            )}
          </div>

          {error && (
            <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-red-400 text-sm">
              {error}
            </div>
          )}

          {/* Hidden inputs */}
          <input ref={pdfInputRef} type="file" accept=".pdf,application/pdf" onChange={handleFileSelect} className="hidden" disabled={isProcessing} />
          <input ref={imageInputRef} type="file" accept="image/jpeg,image/png,image/webp,image/*" onChange={handleFileSelect} className="hidden" disabled={isProcessing} />

          <button onClick={onClose} disabled={isProcessing} className="w-full py-2.5 text-white/40 hover:text-white/70 text-sm transition-colors disabled:opacity-40">
            {t.cancel}
          </button>
        </div>
      </div>
    </div>
  )
}

export default PDFImporter
